"""
Django settings for remitapi project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), os.pardir)) + '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fj_^wq_+k%ea-wd-mg+fnon-0*s*hg=hk3i0#33k^y))2&gi4d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1',' http://127.0.0.1','www.pesapot.com','https://pesapot.com']


APP_NAME = 'Pesa{{Pot}}'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.sites',
    'api',
    'accounts',
    'dashboard',
    'registration',
    'rest_framework',
    'rest_framework.authtoken',
    'background_task',
    'remitapi',
    'pegpay',
    'mtn',
    'docs',
    'ipay',
    'backend',
    'rwanda',
    'tradelance',
    'smart',
    'pesapot_sms',
    'firebase_cloud_msging',
)

# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAdminUser'
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        #'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    # Use Django's standard `django.contrib.auth` permissions,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',

    #'EXCEPTION_HANDLER': 'api.exceptions.api_exception_handler'
}

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'


MIDDLEWARE_CLASSES = (
    'sslify.middleware.SSLifyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)


ROOT_URLCONF = 'remitapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'remitapi.context_processors.global_vars',
            ],
        },
    },
]


WSGI_APPLICATION = 'remitapi.wsgi.application'


# Avatar
GRAVATAR_URL = "https://www.gravatar.com/avatar.php?"

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


BASE_URL = 'https://pesapot.com/'




# DEBUG
DEBUG_API = True
LIVE = 1
DISABLE_COMMS = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

PAGNATION_LIMIT = 10
#celery
BROKER_URL = 'amqp://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

#remitussd
USSDREMIT_KEY = '62816650cfe6d9165371f4f6fb12b90d383ff208'
USSDREMIT_TOKEN = '62816650cfe6d9165371f4f6fb12b90d383ff208'
USSDREMIT_TRANSACTIONSTATUS_URL = 'http://139.162.195.252/api/ussd/trackstatus/'

#useremit
USEREMIT_KEY = '03dcfcb0c178772585f2ede5afa316144ffc8728'
USEREMIT_TOKEN = '03dcfcb0c178772585f2ede5afa316144ffc8728'
USEREMIT_TRANSACTIONSTATUS_URL = 'https://useremit.com/api/payments/bills/status/'

#smart telecom
SMART_ENDPOINT = 'http://154.70.157.64:9090/SmartPesaExtApi/SmartPesaExtApi?wsdl'
SMART_USERNAME = 'TEST'
SMART_PASSWORD = 'Test@2xX16'

# Nexmo sms
NEXMO_USERNAME = ''
NEXMO_PASSWORD = ''
NEXMO_FROM = 'Remit'

#Nexmo sms App
NEXMO_API_KEY = ''
NEXMO_API_SECRET = ''
NEXMO_DEFAULT_FROM = ''

#twilio sms
TWILIO_ACCOUNT_SID=''
TWILIO_AUTH_TOKEN=''
TWILIO_DEFAULT_CALLERID = 'Remit'

#sukuma sms
SUKUMA_SENDER = ""
SUKUMA_USERNAME = ""
SUKUMA_PASSWORD = "admin"
SUKUMA_ENDPOINT = ""
SSLIFY_DISABLE = False

#africa talking sms
AFRICAT_USERNAME = ""
AFRICAT_KEY = ""

#firebase cloud messaging key
FCM_KEY = ''


Beyonic_Callback_URL = ""

RWANDA_USERNAME = ''
RWANDA_PASSWORD = ''
RWANDA_URL = ''
RWANDA_AUTHKEY = ''
RWANDA_SECRET = ''

RWANDA_rdparty = ""
RWANDA_version = ""
RWANDA_DeviceIdentity = ""
RWANDA_DeviceType = ""
RWANDA_DeviceUID = ""
RWANDA_IdentityType = ""


Beyonic_URL = ""
Beyonic_Callback_URL2 =""
BEYONIC_ACCOUNT = ""
Beyonic_USEREMIT_URL = ""

# SMILE_USERNAME = "stone@useremit"
# SMILE_PASSWORD = "reMIT1234"
# SMILE_ENDPOINT = "https://154.73.71.3/TPGW/ThirdPartyGateway?wsdl"

SMILE_USERNAME = ""
SMILE_PASSWORD = ""
SMILE_ENDPOINT = ""

SMILE_FromAccountId = ""

SESSION_COOKIE_AGE = 30 * 60

try:
    from local_settings import *
except ImportError:
    pass


STATIC_URL = '%sstatic/' % BASE_URL

STATIC_ROOT = '%sstatic/' % BASE_DIR

MEDIA_URL = '%sstatic/media/' % BASE_URL

MEDIA_ROOT = '%sstatic/media/' % BASE_DIR

EMAIL_TEMPLATE_DIR = '%sstatic/emails/' % BASE_DIR

LOGIN_REDIRECT_URL = BASE_URL

TRADELANCE_ENDPOINT = 'http://52.36.218.248/api/index.php'
TRADELANCE_USERNAME = 'redcore'
TRADELANCE_PASSWORD = 'r3dc0r3'
