API_RESPONSE = {}

API_RESPONSE[0] = u"Request Successfull"
API_RESPONSE[1] = u"Subscriber not registered for Mobile Money"
API_RESPONSE[2] = u"Subscriber is not fully registered"
API_RESPONSE[3] = u"Subscriber is fully registered"
API_RESPONSE[4] = u"Deposit money Transaction Successfull"
API_RESPONSE[5] = u"Withdraw money Transaction Successfull"
API_RESPONSE[6] = u"Phonenumber is not valid for this network, be sure to start the Phonenumber with a valid country code e.g 256"
API_RESPONSE[7] = u"API Parameters missing or invalid"
API_RESPONSE[8] = u"Service is currently unavailable"
API_RESPONSE[9] = u"Request Unsuccessfull"
API_RESPONSE[
    10] = u"An Error occurred on our end, we have been notified and are looking into it"
API_RESPONSE[11] = u"You have insufficient balance on your Account"
API_RESPONSE[12] = u"This country is not supported"
API_RESPONSE[13] = u"This network code is not supported"
API_RESPONSE[14] = u"Service not supported for this account"
API_RESPONSE[
    15] = u"Transaction pending, we will update you once the Transaction has been processed"
API_RESPONSE[16] = u"The Payment is below the allowed minimum"
API_RESPONSE[17] = u"The Subscriber is not registered for mobile money"
API_RESPONSE[18] = u"Transaction failed. Consult customer care for details."
API_RESPONSE[19]=u"Pending subscriber approval"
API_RESPONSE[20]=u"Transaction Error"
API_RESPONSE[21]=u"client key already exists"
API_RESPONSE[22]=u"Client with that name already exists"
